/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as FinRouteImport } from './routes/fin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SommaireRouteImport } from './routes/sommaire'
import { Route as LireSlugRouteImport } from './routes/lire.$slug'
import { Route as LivreBookRouteImport } from './routes/livre.$book'
import { Route as LivreBookIndexRouteImport } from './routes/livre.$book.index'
import { Route as LivreBookCarteRouteImport } from './routes/livre.$book.carte'
import { Route as LivreBookFinRouteImport } from './routes/livre.$book.fin'
import { Route as LivreBookSommaireRouteImport } from './routes/livre.$book.sommaire'
import { Route as LivreBookLireSlugRouteImport } from './routes/livre.$book.lire.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const FinRoute = FinRouteImport.update({
  id: '/fin',
  path: '/fin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SommaireRoute = SommaireRouteImport.update({
  id: '/sommaire',
  path: '/sommaire',
  getParentRoute: () => rootRouteImport,
} as any)
const LireSlugRoute = LireSlugRouteImport.update({
  id: '/lire/$slug',
  path: '/lire/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreBookRoute = LivreBookRouteImport.update({
  id: '/livre/$book',
  path: '/livre/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreBookIndexRoute = LivreBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LivreBookRoute,
} as any)
const LivreBookCarteRoute = LivreBookCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => LivreBookRoute,
} as any)
const LivreBookFinRoute = LivreBookFinRouteImport.update({
  id: '/fin',
  path: '/fin',
  getParentRoute: () => LivreBookRoute,
} as any)
const LivreBookSommaireRoute = LivreBookSommaireRouteImport.update({
  id: '/sommaire',
  path: '/sommaire',
  getParentRoute: () => LivreBookRoute,
} as any)
const LivreBookLireSlugRoute = LivreBookLireSlugRouteImport.update({
  id: '/lire/$slug',
  path: '/lire/$slug',
  getParentRoute: () => LivreBookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/carte': typeof CarteRoute
  '/fin': typeof FinRoute
  '/login': typeof LoginRoute
  '/sommaire': typeof SommaireRoute
  '/lire/$slug': typeof LireSlugRoute
  '/livre/$book': typeof LivreBookRouteWithChildren
  '/livre/$book/carte': typeof LivreBookCarteRoute
  '/livre/$book/fin': typeof LivreBookFinRoute
  '/livre/$book/sommaire': typeof LivreBookSommaireRoute
  '/livre/$book/': typeof LivreBookIndexRoute
  '/livre/$book/lire/$slug': typeof LivreBookLireSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/carte': typeof CarteRoute
  '/fin': typeof FinRoute
  '/login': typeof LoginRoute
  '/sommaire': typeof SommaireRoute
  '/lire/$slug': typeof LireSlugRoute
  '/livre/$book/carte': typeof LivreBookCarteRoute
  '/livre/$book/fin': typeof LivreBookFinRoute
  '/livre/$book/sommaire': typeof LivreBookSommaireRoute
  '/livre/$book': typeof LivreBookIndexRoute
  '/livre/$book/lire/$slug': typeof LivreBookLireSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/carte': typeof CarteRoute
  '/fin': typeof FinRoute
  '/login': typeof LoginRoute
  '/sommaire': typeof SommaireRoute
  '/lire/$slug': typeof LireSlugRoute
  '/livre/$book': typeof LivreBookRouteWithChildren
  '/livre/$book/carte': typeof LivreBookCarteRoute
  '/livre/$book/fin': typeof LivreBookFinRoute
  '/livre/$book/sommaire': typeof LivreBookSommaireRoute
  '/livre/$book/': typeof LivreBookIndexRoute
  '/livre/$book/lire/$slug': typeof LivreBookLireSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/carte'
    | '/fin'
    | '/login'
    | '/sommaire'
    | '/lire/$slug'
    | '/livre/$book'
    | '/livre/$book/carte'
    | '/livre/$book/fin'
    | '/livre/$book/sommaire'
    | '/livre/$book/'
    | '/livre/$book/lire/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/carte'
    | '/fin'
    | '/login'
    | '/sommaire'
    | '/lire/$slug'
    | '/livre/$book/carte'
    | '/livre/$book/fin'
    | '/livre/$book/sommaire'
    | '/livre/$book'
    | '/livre/$book/lire/$slug'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/carte'
    | '/fin'
    | '/login'
    | '/sommaire'
    | '/lire/$slug'
    | '/livre/$book'
    | '/livre/$book/carte'
    | '/livre/$book/fin'
    | '/livre/$book/sommaire'
    | '/livre/$book/'
    | '/livre/$book/lire/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CarteRoute: typeof CarteRoute
  FinRoute: typeof FinRoute
  LoginRoute: typeof LoginRoute
  SommaireRoute: typeof SommaireRoute
  LireSlugRoute: typeof LireSlugRoute
  LivreBookRoute: typeof LivreBookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin': {
      id: '/fin'
      path: '/fin'
      fullPath: '/fin'
      preLoaderRoute: typeof FinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sommaire': {
      id: '/sommaire'
      path: '/sommaire'
      fullPath: '/sommaire'
      preLoaderRoute: typeof SommaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lire/$slug': {
      id: '/lire/$slug'
      path: '/lire/$slug'
      fullPath: '/lire/$slug'
      preLoaderRoute: typeof LireSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre/$book': {
      id: '/livre/$book'
      path: '/livre/$book'
      fullPath: '/livre/$book'
      preLoaderRoute: typeof LivreBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre/$book/': {
      id: '/livre/$book/'
      path: '/'
      fullPath: '/livre/$book/'
      preLoaderRoute: typeof LivreBookIndexRouteImport
      parentRoute: typeof LivreBookRoute
    }
    '/livre/$book/carte': {
      id: '/livre/$book/carte'
      path: '/carte'
      fullPath: '/livre/$book/carte'
      preLoaderRoute: typeof LivreBookCarteRouteImport
      parentRoute: typeof LivreBookRoute
    }
    '/livre/$book/fin': {
      id: '/livre/$book/fin'
      path: '/fin'
      fullPath: '/livre/$book/fin'
      preLoaderRoute: typeof LivreBookFinRouteImport
      parentRoute: typeof LivreBookRoute
    }
    '/livre/$book/sommaire': {
      id: '/livre/$book/sommaire'
      path: '/sommaire'
      fullPath: '/livre/$book/sommaire'
      preLoaderRoute: typeof LivreBookSommaireRouteImport
      parentRoute: typeof LivreBookRoute
    }
    '/livre/$book/lire/$slug': {
      id: '/livre/$book/lire/$slug'
      path: '/lire/$slug'
      fullPath: '/livre/$book/lire/$slug'
      preLoaderRoute: typeof LivreBookLireSlugRouteImport
      parentRoute: typeof LivreBookRoute
    }
  }
}

interface LivreBookRouteChildren {
  LivreBookCarteRoute: typeof LivreBookCarteRoute
  LivreBookFinRoute: typeof LivreBookFinRoute
  LivreBookSommaireRoute: typeof LivreBookSommaireRoute
  LivreBookIndexRoute: typeof LivreBookIndexRoute
  LivreBookLireSlugRoute: typeof LivreBookLireSlugRoute
}

const LivreBookRouteChildren: LivreBookRouteChildren = {
  LivreBookCarteRoute: LivreBookCarteRoute,
  LivreBookFinRoute: LivreBookFinRoute,
  LivreBookSommaireRoute: LivreBookSommaireRoute,
  LivreBookIndexRoute: LivreBookIndexRoute,
  LivreBookLireSlugRoute: LivreBookLireSlugRoute,
}

const LivreBookRouteWithChildren = LivreBookRoute._addFileChildren(
  LivreBookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CarteRoute: CarteRoute,
  FinRoute: FinRoute,
  LoginRoute: LoginRoute,
  SommaireRoute: SommaireRoute,
  LireSlugRoute: LireSlugRoute,
  LivreBookRoute: LivreBookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
